### ISSUE TITLE
Stickers

### ISSUE THREAD

**Issue by iandees** [openaddresses/openaddresses-ops#13]
I have ~200 stickers that I bought from Stickermule. They look like this:

![image](https://cloud.githubusercontent.com/assets/261584/15030946/49bc6ef0-1223-11e6-8fcc-0b4549f27b57.png)

Two questions:

1. Do you want some? Send me an email and I'll send you some in the mail. Apologies to the folks who have previously requested some – this time I'll actually get to the post office 😄 .
2. What other cool sticker designs should we come up with?

**Comment by migurski** [comment]
Send a bunch to Mapzen in SF! 201 Spear St. #1600, SF CA 94105.

**Comment by dianashk** [comment]
Send some to Mapzen NYC as well pretty please! 🎉 

🏠 🏣 🏥 🏡 

`30 W 26th Street, New York, NY 10010`

**Comment by sbma44** [comment]
Belatedly: I'd love some! `1714 14th St NW Rear Entrance, Washington DC 20009`

**Comment by iandees** [comment]
I sent 4 envelopes today! Hopefully they all make it.

**Comment by migurski** [comment]
Stickers exist! Closing this issue.
