### ISSUE TITLE
Proposal: rename "type" tags in source schema

### ISSUE THREAD

**Issue by migurski** [openaddresses/openaddresses-ops#16]
We use the term "type" in two places to mean different things [in our source schema](https://github.com/openaddresses/openaddresses/blob/14d0309bfc63c74693a978269d50973254bea4d0/CONTRIBUTING.md):

1. [As a core tag](https://github.com/openaddresses/openaddresses/blob/14d0309bfc63c74693a978269d50973254bea4d0/CONTRIBUTING.md#core-tags):
    
    > A string containing the protocol (One of: http, ftp, ESRI)
2. [As a processing tag](https://github.com/openaddresses/openaddresses/blob/14d0309bfc63c74693a978269d50973254bea4d0/CONTRIBUTING.md#processing-tags):
    
    > The type properties stores the format. It can currently be one of gdb, shapefile, shapefile-polygon, csv, geojson, or xml (for GML).

I’d like to propose that we phase out the use of "type" and replace it with two separate tags whose meanings will be more clear: "protocol" and "format". We can maintain backward compatibility for some period of time, but ultimately "type" should be deprecated and removed. A source [like Juneau, AK](https://github.com/openaddresses/openaddresses/blob/14d0309bfc63c74693a978269d50973254bea4d0/sources/us/ak/city_of_juneau.json) currently looks like this:

```
{
    "coverage": { … },
    "data": "https://ftp.ci.juneau.ak.us/pub/CBJ_GIS_map_layers/juneau_alaska_gis_internet_parcel_layer.zip",
    "type": "http",
    "compression": "zip",
    "conform": {
        "type": "shapefile-polygon",
        "number": { … },
        "street": { … }
    }
}
```

It would instead look like this:

```
{
    "coverage": { … },
    "data": "https://ftp.ci.juneau.ak.us/pub/CBJ_GIS_map_layers/juneau_alaska_gis_internet_parcel_layer.zip",
    "protocol": "http",
    "compression": "zip",
    "conform": {
        "format": "shapefile-polygon",
        "number": { … },
        "street": { … }
    }
}
```

**Comment by NelsonMinar** [comment]
👍

Is protocol even necessary, or can it be inferred from the data URL?

**Comment by migurski** [comment]
In theory yes, though ESRI URLs will start with "http://" as well.

**Comment by NelsonMinar** [comment]
Oh right. That suggests the directive we want here is something like "download single file" vs "scrape ESRI endpoint". I may be overthinking your proposed change.

**Comment by ingalls** [comment]
This happened! :tada:
