### ISSUE TITLE
improve OSM wiki OpenAddresses page

### ISSUE THREAD

**Issue by sbma44** [openaddresses/openaddresses-ops#20]
[Recent edits](http://wiki.openstreetmap.org/w/index.php?title=OpenAddresses.io&type=revision&diff=1508353&oldid=1207100) to the OSM wiki page for OpenAddresses cast our project in an unflattering light while also raising valid concerns about how we've communicated about the project. In the interest of encouraging more collaboration between OSM and OA, I'd like to suggest that we make the following edits to that page:

- Expand the list of contributors to include @migurski, @NelsonMinar, @nvkelso, @trescube, @slibby, @sergiyprotsiv, @justinelliotmeyers and anyone else who cares to be included (please strike your name or otherwise note if you would prefer not to be attributed)
- Acknowledge the participation of Mapzen and Mapbox employees and the donation of storage by AWS
- Remove the assertion that we "[do] not validate entries submitted to it in any form" -- it's incorrect.
- Remove the assertion that the project "contains everything from legit open data to data obtain by potentially criminal acts". The implication seems to me to be that we knowingly engage in criminal conduct, which is untrue. "Potentially criminal" is a uselessly broad characterization and of course applies equally to OSM data.
- Move liability disclaimer to its own section, restate & expand to a more generic "use at your own risk" and acknowledgement that OA makes a good faith effort to characterize & classify license terms but, like OSM, does not always use trained lawyers to evaluate data licenses.
- Move license validation and import guideline links to "Adding OpenAddresses Data to OpenStreetMap" section (it's good advice!)
- correct "with other words" typo
- add any more talks we've got -- I have [this one](https://vimeo.com/142988441), please drop links if you've got em!

I'm happy to take this on. If folks find these changes agreeable we should probably consider updating the openaddresses.io site to address the concerns raised by these wiki edits.

**Comment by iandees** [comment]
I made [this change](https://wiki.openstreetmap.org/w/index.php?title=OpenAddresses.io&type=revision&diff=1529660&oldid=1508353) before seeing this excellent list of things to change. Please feel free to expand on what I did, @sbma44.

**Comment by nvkelso** [comment]
Great suggestions, thanks for taking this on!

**Comment by sbma44** [comment]
Great. I'll give folks today to notice this ticket and opt out of being added to the wiki page, then will proceed with some edits.

**Comment by iandees** [comment]
A response from Nakaner on my user talk page: https://wiki.openstreetmap.org/w/index.php?title=User_talk:Yellowbkpk&diff=next&oldid=967765

**Comment by migurski** [comment]
I’m happy to be added. Thanks for creating this issue, @sbma44.

**Comment by NelsonMinar** [comment]
Please feel free to add me as a contributor.

**Comment by sergiyprotsiv** [comment]
Sure, please add me too. Thanks!

**Comment by nvkelso** [comment]
Justin also contributes both to OSM and OA.

**Comment by sbma44** [comment]
edited OP to include him

**Comment by justinelliotmeyers** [comment]
Thanks for including me; I have talked to Simon in the past about Switzerland data for OA, and he is on the board of this: https://sosm.ch/projects/swiss-open-addresses/

Let me know how I can help. Thanks

**Comment by sbma44** [comment]
went ahead with it -- additional tweaks welcome, please feel free to reopen https://wiki.openstreetmap.org/w/index.php?title=OpenAddresses.io&type=revision&diff=1529970&oldid=1529729

**Comment by nvkelso** [comment]
I’m trying to add at the bottom, but saving always errors for me on their
wiki:

  Talks and Presentations

   - OpenAddresses has 440M points. How can we tell when we’re done?
   <https://blog.mapbox.com/openaddresses-has-440m-points-how-can-we-tell-when-were-done-caccd4a4c16d>
   a blog post by Michal Migurski for Mapbox in 2017
   -

   OpenAddresses celebrates 400 million addresses
   <https://mapzen.com/blog/openaddresses-celebrates-400-million-addresses/>
   a blog post by Nathaniel V. Kelso, Stephen Hess, Justin Meyers, Ian Dees,
   and Michal Migurski at Mapzen in 2017
   -

   OpenAddresses: A collection of open address data
   <https://www.youtube.com/watch?v=yeGwD9-hxoU> - a talk by Ian Dees at
   FOSS4G NA 2016 in Raleigh, NC, USA
   -

   Opening Address Data Around The World <https://vimeo.com/142988441> - a
   talk by Tom Lee at FOSS4G 2015 in Seoul
   -

   AWS Symposium <https://youtu.be/ACFdSEU6nxM?t=828> - a talk by Ian Dees
   at AWS Government, Education, and Nonprofits Symposium in Washington, DC
   USA, June 2015
   -

   Unlocking Open Data with the Power of Search
   <https://www.youtube.com/watch?v=ffFBtX8BCHY> - Ian Dees, Mike Migurski,
   Diana Shkolnikov at Code for America Summit 2015
   -

   Mapzen's Support for Code for America and OpenAddresses
   <https://mapzen.com/blog/mapzens-support-for-code-for-america-and-openaddresses/>
   a blog post by Michal Migurski at Mapzen in 2015
   -

   Video of a talk about OpenAddresses
   <http://www.youtube.com/watch?v=lzNRU9vub04&t=9m30s> - a lightning talk
   by Alex Barth at SOTM EU 2014

**Comment by sbma44** [comment]
@nvkelso I had to log out & back in again to have mediawiki set my permissions properly & let me save (you need a confirmed email address, too)

**Comment by nvkelso** [comment]
Logging out and back in a few times solved it, omg.

**Comment by trescube** [comment]
CONTENTS OF WIKI PAGE:

{{warning|OpenAddresses.io data is not suitable for import to OpenStreetMap without additional review and adherence to the OSM [[Import/Guidelines|import guidelines]]. Please see below for more detail.}}

''See [[OpenAddresses]] for other address collection projects''

'''OpenAddresses.io,''' often referred to as simply "OpenAddresses", is "a global collection of address data sources, open and free to use" which was created by OSMers [[User:Yellowbkpk|Ian Dees]], [[User:Ingalls|Nick Ingalls]], Mike Migurski, [https://github.com/openaddresses/openaddresses/graphs/contributors and others]. Originally a spreadsheet of government address datasets maintained by Dees, it now has an aggregated download, an API, and a website at [http://openaddresses.io openaddresses.io]. The project's data store and collaboration center is [https://github.com/openaddresses its Github repository].

At least two other projects exist that share the name "OpenAddresses," but OpenAddresses.io is the largest by territory covered, source count (2,100+) and total addresses (470+ million).

=== Importing OpenAddresses Data To OpenStreetMap ===
OpenAddresses is a useful way to find openly licensed address datasets, some of which may be appropriate candidates for addition to OpenStreetMap. But a data source's presence within the OpenAddresses project should not be interpreted as proof than importing it to OpenStreetMap is appropriate. Each individual data source's original license must first be reviewed for compatibility with OpenStreetMap. If that review determines the licenses are compatible, the [[Import/Guidelines|OSM import guidelines]] must then be followed.

=== OpenAddresses Data, Licensing and Liability ===
OpenAddresses' metadata and list of sources is offered under a [https://creativecommons.org/publicdomain/zero/1.0/ CC0] license. The datasets indexed by OpenAddresses are licensed under many different terms by their publishers, from well-known Creative Commons licenses to idiosyncratic documents used nowhere else. OpenAddresses contributors make a good-faith effort to ensure that the data sources the project indexes are available under open licenses that fit within with broadly-defined "Freely Shareable" or "Share-Alike Required" categories.  However, like OpenStreetMap, the OpenAddresses volunteers making these determinations are rarely trained lawyers. OpenAddresses does not offer indemnity or other guarantees to users of the data it indexes. Use of OpenAddresses data is at the user's own risk. A data source being accepted under OpenAddresses' sense of "open licensing" does not mean it is compatible with the [[Open Database License|ODbL]] used by OpenStreetMap.

=== Contributors and Supporters ===
Notable active contributors include Nathaniel V. Kelso, Nelson Minar, Stephen Hess, Sam Libby, Sergiy Protsiv and Justin Meyers. The project's primary Github repository has received contributions from over 120 individuals. Although many of its contributors are also active OpenStreetMap contributors, OpenAddresses.io is not associated with OpenStreetMap or the OpenStreetMap Foundation.

Usage of the project's data is not tracked, so a complete list of individuals and companies using OpenAddresses data does not exist. But the project is actively supported by staff from both [[Mapzen]] and [[Mapbox]]. Amazon Web Services donates storage and computing services to the project.

=== Talks and Presentations ===
* [https://blog.mapbox.com/openaddresses-has-440m-points-how-can-we-tell-when-were-done-caccd4a4c16d OpenAddresses has 440M points. How can we tell when we’re done?] - a blog post by Michal Migurski for Mapbox in 2017
* [https://mapzen.com/blog/openaddresses-celebrates-400-million-addresses/ OpenAddresses celebrates 400 million addresses] - a blog post by Nathaniel V. Kelso, Stephen Hess, Justin Meyers, Ian Dees, and Michal Migurski at Mapzen in 2017
* [https://www.youtube.com/watch?v=yeGwD9-hxoU OpenAddresses: A collection of open address data] - a talk by Ian Dees at FOSS4G NA 2016 in Raleigh, NC, USA
* [https://vimeo.com/142988441 Opening Address Data Around The World] - a talk by Tom Lee at FOSS4G 2015 in Seoul
* [https://youtu.be/ACFdSEU6nxM?t=828 AWS Symposium] - a talk by Ian Dees at AWS Government, Education, and Nonprofits Symposium in Washington, DC USA, June 2015
* [https://www.youtube.com/watch?v=ffFBtX8BCHY Unlocking Open Data with the Power of Search] - Ian Dees, Mike Migurski, Diana Shkolnikov at Code for America Summit 2015
* [https://mapzen.com/blog/mapzens-support-for-code-for-america-and-openaddresses/ Mapzen's Support for Code for America and OpenAddresses] - a blog post by Michal Migurski at Mapzen in 2015
* [http://www.youtube.com/watch?v=lzNRU9vub04&t=9m30s Video of a talk about OpenAddresses] - a lightning talk by Alex Barth at SOTM EU 2014
