### ISSUE TITLE
moving oa2osm into openaddresses org

### ISSUE THREAD

**Issue by andrewharvey** [openaddresses/openaddresses-ops#24]
@openaddresses/administrators I think it makes sense for me to move https://github.com/andrewharvey/oa2osm into the openaddresses organisation? Is that a good idea? I don't have permissions to do so, so would need someone to adjust that.

**Comment by iandees** [comment]
Sure, if you want to transfer ownership to me I can transfer it into OA.

**Comment by andrewharvey** [comment]
@iandees Do you think I could be given permission in the `openaddresses` org so I can directly transfer straight to `openaddresses`?

**Comment by iandees** [comment]
Sure thing.

**Comment by iandees** [comment]
I enabled the ability for members to create new repositories in OA org, and you're already a member. In theory you should be able to move it over now. Let me know if that doesn't work.

**Comment by andrewharvey** [comment]
Thanks @iandees all good.
