### ISSUE TITLE
Data Mirrors

### ISSUE THREAD

**Issue by buildscientist** [openaddresses/openaddresses-ops#28]
Hello, 

Thank you for all the time and effort you put into managing this free data set. 

I was wondering if there are any mirrors to https://data.openaddresses.io/ ? I'm not sure if the data is backed by AWS S3 but download times seem to fairly long due to throttling. 

I understand that this may be deliberate because this is donor funded project but has any thought been put into creating official mirrors of the data set?

**Comment by iandees** [comment]
The data is stored on S3, yep. Downloads via data.openaddresses.io HTTPS are throttled to reduce bandwidth costs.

If you're on AWS, you can use the requester pays S3 feature to download directly from the data.openaddresses.io bucket.
